# Generated by Django 3.0.4 on 2020-03-19 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insira o nome da marca.', max_length=200, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insira o nome da categoria.', max_length=200, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Equipament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimony', models.CharField(blank=True, help_text='Insira o patrimônio do equipamento.', max_length=8, null=True, unique=True, verbose_name='Patrimônio')),
                ('description', models.TextField(help_text='Insira uma descrição do equipamento.', max_length=1000, verbose_name='Descrição')),
                ('warranty_start', models.DateField(verbose_name='Início da Garantia')),
                ('warranty_end', models.DateField(verbose_name='Fim da Garantia')),
                ('acquisition_date', models.DateField(verbose_name='Data de Aquisição')),
                ('acquisition_value', models.FloatField(verbose_name='Valor de Aquisição')),
                ('status', models.CharField(choices=[('u', 'Usado'), ('a', 'Almoxarifado'), ('e', 'Estaleiro'), ('s', 'Sucata'), ('d', 'Doação')], default='a', max_length=1, verbose_name='Status de uso')),
                ('brand', models.ForeignKey(help_text='Selecione a marca do equipamento.', on_delete=django.db.models.deletion.PROTECT, to='api.Brand', verbose_name='Marca')),
                ('category', models.ForeignKey(help_text='Selecione a categoria do equipamento.', on_delete=django.db.models.deletion.PROTECT, to='api.Category', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insira a descrição do andar do pedrio.', max_length=100, verbose_name='Andar')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insira o nome da modelo.', max_length=200, verbose_name='Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('equipament_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Equipament')),
                ('policy', models.BooleanField(help_text='Marque se o computador está na política da procuradoria.', verbose_name='Política')),
                ('status_zenworks', models.BooleanField(default=False, help_text='Marque se o computador está sendo monitorado pelo Zenworks.', verbose_name='Status do Zenworks')),
                ('status_trend', models.BooleanField(default=False, help_text='Marque se o computador está sendo monitorado pelo TREND.', verbose_name='Status do TREND')),
                ('status_wsus', models.BooleanField(default=False, help_text='Marque se o computador está sendo monitorado pelo WSUS.', verbose_name='Status do WSUS')),
            ],
            bases=('api.equipament',),
        ),
        migrations.CreateModel(
            name='UA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(help_text='Insira o código da unidade administrativa.', unique=True, verbose_name='Código da UA')),
                ('name', models.CharField(help_text='Insira o nome da unidade administrativa.', max_length=200, verbose_name='Nome da UA')),
                ('floor', models.ForeignKey(blank=True, help_text='Selecione o andar da unidade administrativa.', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Floor')),
            ],
        ),
        migrations.AddField(
            model_name='equipament',
            name='floor',
            field=models.ForeignKey(blank=True, help_text='Selecione o andar em que o equipamento se encontra.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Floor', verbose_name='Andar'),
        ),
        migrations.AddField(
            model_name='equipament',
            name='model',
            field=models.ForeignKey(help_text='Selecione o modelo do equipamento.', on_delete=django.db.models.deletion.PROTECT, to='api.Model', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='equipament',
            name='ua',
            field=models.ForeignKey(blank=True, help_text='Selecione a unidade administrativa onde o equipamento se encontra.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.UA', verbose_name='Unidade Administrativa'),
        ),
    ]
