# Generated by Django 3.0.4 on 2020-05-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('Usado', 'Usado'), ('Almoxarifado', 'Almoxarifado'), ('Estaleiro', 'Estaleiro'), ('Sucata', 'Sucata'), ('Doação', 'Doação')], default='Usado', max_length=12, verbose_name='Status de uso'),
        ),
        migrations.AlterField(
            model_name='equipament',
            name='status',
            field=models.CharField(choices=[('Usado', 'Usado'), ('Almoxarifado', 'Almoxarifado'), ('Estaleiro', 'Estaleiro'), ('Sucata', 'Sucata'), ('Doação', 'Doação')], default='Usado', max_length=12, verbose_name='Status de uso'),
        ),
    ]
