# Generated by Django 3.0.4 on 2020-03-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200323_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='Insira o nome da marca.', max_length=200, unique=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Insira o nome da categoria.', max_length=200, unique=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='equipament',
            name='ua',
            field=models.ForeignKey(blank=True, help_text='Selecione a unidade administrativa onde o equipamento se encontra.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Ua', verbose_name='Unidade Administrativa'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.CharField(help_text='Insira a descrição do andar do pedrio.', max_length=100, unique=True, verbose_name='Andar'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(help_text='Insira o nome da modelo.', max_length=200, unique=True, verbose_name='Modelo'),
        ),
    ]
