# Generated by Django 3.0.4 on 2020-04-06 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200327_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipament',
            name='description',
        ),
        migrations.AlterField(
            model_name='computer',
            name='policy',
            field=models.BooleanField(default=False, help_text='Marque se o computador está na política da procuradoria.', verbose_name='Política'),
        ),
        migrations.AlterField(
            model_name='equipament',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aquisição'),
        ),
        migrations.AlterField(
            model_name='equipament',
            name='acquisition_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor de Aquisição'),
        ),
        migrations.AlterField(
            model_name='equipament',
            name='status',
            field=models.CharField(choices=[('u', 'Usado'), ('a', 'Almoxarifado'), ('e', 'Estaleiro'), ('s', 'Sucata'), ('d', 'Doação')], default='u', max_length=1, verbose_name='Status de uso'),
        ),
        migrations.AlterField(
            model_name='equipament',
            name='ua',
            field=models.ForeignKey(blank=True, help_text='Selecione a unidade administrativa onde o equipamento se encontra.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Ua', verbose_name='Unidade Administrativa'),
        ),
    ]
