# Generated by Django 3.0.4 on 2020-04-06 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200406_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipament',
            name='ua',
            field=models.ForeignKey(blank=True, help_text='Selecione a unidade administrativa onde o equipamento se encontra.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Ua', verbose_name='Unidade Administrativa'),
        ),
        migrations.AlterField(
            model_name='equipament',
            name='warranty_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da Garantia'),
        ),
        migrations.AlterField(
            model_name='equipament',
            name='warranty_start',
            field=models.DateField(blank=True, null=True, verbose_name='Início da Garantia'),
        ),
    ]
