# Generated by Django 3.0.4 on 2020-04-06 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200406_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipament',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Selecione a marca do equipamento.', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='equipament',
            name='ua',
            field=models.ForeignKey(blank=True, help_text='Selecione a unidade administrativa onde o equipamento se encontra.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Ua', verbose_name='Unidade Administrativa'),
        ),
    ]
