# Generated by Django 3.0.4 on 2020-04-07 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200407_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='policy',
            field=models.BooleanField(blank=True, default=False, help_text='Marque se o computador está na política da procuradoria.', null=True, verbose_name='Política'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='status_trend',
            field=models.BooleanField(blank=True, default=False, help_text='Marque se o computador está sendo monitorado pelo TREND.', null=True, verbose_name='Status do TREND'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='status_wsus',
            field=models.BooleanField(blank=True, default=False, help_text='Marque se o computador está sendo monitorado pelo WSUS.', null=True, verbose_name='Status do WSUS'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='status_zenworks',
            field=models.BooleanField(blank=True, default=False, help_text='Marque se o computador está sendo monitorado pelo Zenworks.', null=True, verbose_name='Status do Zenworks'),
        ),
        migrations.AlterField(
            model_name='equipament',
            name='ua',
            field=models.ForeignKey(blank=True, help_text='Selecione a unidade administrativa onde o equipamento se encontra.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Ua', verbose_name='Unidade Administrativa'),
        ),
    ]
