# Generated by Django 3.0.4 on 2020-04-28 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200428_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipament',
            name='ua',
            field=models.ForeignKey(blank=True, help_text='Selecione a unidade administrativa onde o equipamento se encontra.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Ua', verbose_name='Unidade Administrativa'),
        ),
    ]
