# Generated by Django 3.0.4 on 2020-04-30 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200429_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipament',
            name='ua',
            field=models.ForeignKey(blank=True, help_text='Selecione a unidade administrativa onde o equipamento se encontra.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Ua', verbose_name='Unidade Administrativa'),
        ),
        migrations.AlterField(
            model_name='ua',
            name='name',
            field=models.CharField(help_text='Insira o nome da unidade administrativa.', max_length=200, unique=True, verbose_name='Nome da UA'),
        ),
    ]
