# Generated by Django 3.0.4 on 2020-05-06 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200430_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipament',
            name='ua',
            field=models.ForeignKey(blank=True, help_text='Selecione a unidade administrativa onde o equipamento se encontra.', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Ua', verbose_name='Unidade Administrativa'),
        ),
        migrations.AlterField(
            model_name='ua',
            name='floor',
            field=models.ForeignKey(blank=True, help_text='Selecione o andar da unidade administrativa.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Floor'),
        ),
    ]
