# Generated by Django 3.0.4 on 2020-05-12 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200506_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipament',
            name='ua',
            field=models.ForeignKey(blank=True, help_text='Selecione a unidade administrativa onde o equipamento se encontra.', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Ua', verbose_name='Unidade Administrativa'),
        ),
    ]
